### ISSUE TITLE
Enable browser name parameter as command line argument

### ISSUE THREAD

**Issue by build-failure** [automate-website/jwebrobot#31]
**Acceptance Criteria**
1. _firefox_ & _chrome_ are valid argument values
2. argument name is _browser_

**Comment by dimw** [comment]
It is still required to pass `-Dwebdriver.chrome.driver=<path to chrome driver>` property. Let's investigate, whether we should substitute it by our own option (e.g. `--chromeDriver=<path to chrome driver>`).
